### ISSUE TITLE
Unable to locate a class or view for component [plugins-payment::payment-method]

### ISSUE THREAD

**Issue by vodinhht20** [FriendsOfBotble/fob-sepay#1]
![image](https://github.com/FriendsOfBotble/fob-sepay/assets/71485569/6f5089a4-585d-46d4-a623-cf83c0461b53)

**Comment by dinhquochan** [comment]
Hi,

What is your Botble variant? What version are you using?

**Comment by vodinhht20** [comment]
My Botble application version is 1.21.8 and it is using the Nest theme.

my setting:
![image](https://github.com/FriendsOfBotble/fob-sepay/assets/71485569/1e455285-4251-40fd-a38f-77543e26bcc8)

**Comment by dinhquochan** [comment]
Hi @vodinhht20, 

This version might not include the payment component used by SePay. The latest version is 1.23.6. Please update to the latest version and try again.

**Comment by sangnguyenplus** [comment]
Hi @vodinhht20,

We have just released a new version https://github.com/FriendsOfBotble/fob-sepay/releases/tag/v1.0.8 to support your version.

Try to go to Plugins → Installed plugins and update SePay plugin, then it should be fixed.
